//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.VeiculoZ.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class ConstantesDados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ConstantesDados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Midas.VeiculoZ.Recursos.ConstantesDados", typeof(ConstantesDados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update abastecimento set idposto=@idposto, data=@data, observacoes=@observacoes, tanquecheio=@tanquecheio, idtipoabastecimento=@idtipoabastecimento, valor=@valor, valorlitro=@valorlitro where id = @id.
        /// </summary>
        internal static string AtualizarAbastecimento {
            get {
                return ResourceManager.GetString("AtualizarAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update distribuidora set nome = @nome where id = @id.
        /// </summary>
        internal static string AtualizarDistribuidora {
            get {
                return ResourceManager.GetString("AtualizarDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update percurso set odometroinicial = @odometroinicial, odometrofinal = @odometrofinal, idveiculo=@idveiculo, viagem=@viagem, idabastecimentoinicial=@idabastecimentoinicial, idabastecimentofinal=@idabastecimentofinal where id = @id.
        /// </summary>
        internal static string AtualizarPercurso {
            get {
                return ResourceManager.GetString("AtualizarPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update posto set idpessoajuridica=@idpessoajuridica, iddistribuidora=@iddistribuidora, idendereco=@idendereco, observacoes=@observacoes where id = @id.
        /// </summary>
        internal static string AtualizarPosto {
            get {
                return ResourceManager.GetString("AtualizarPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update tipocombustivel set nome = @nome where id = @id.
        /// </summary>
        internal static string AtualizarTipoCombustivel {
            get {
                return ResourceManager.GetString("AtualizarTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update veiculo set placa=@placa, renavam=@renavam, cor=@cor, modelo=@modelo, marca=@marca where id = @id.
        /// </summary>
        internal static string AtualizarVeiculo {
            get {
                return ResourceManager.GetString("AtualizarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from abastecimento where id = @id.
        /// </summary>
        internal static string ExcluirAbastecimento {
            get {
                return ResourceManager.GetString("ExcluirAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from distribuidora where id = @id.
        /// </summary>
        internal static string ExcluirDistribuidora {
            get {
                return ResourceManager.GetString("ExcluirDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from percurso where id = @id.
        /// </summary>
        internal static string ExcluirPercurso {
            get {
                return ResourceManager.GetString("ExcluirPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from posto where id = @id.
        /// </summary>
        internal static string ExcluirPosto {
            get {
                return ResourceManager.GetString("ExcluirPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from tipocombustivel where id = @id.
        /// </summary>
        internal static string ExcluirTipoCombustivel {
            get {
                return ResourceManager.GetString("ExcluirTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from veiculo where id = @id.
        /// </summary>
        internal static string ExcluirVeiculo {
            get {
                return ResourceManager.GetString("ExcluirVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into abastecimento (idposto,data,observacoes,tanquecheio,idtipoabastecimento,valor,valorlitro) values (@idposto,@data,@observacoes,@tanquecheio,@idtipoabastecimento,@valor,@valorlitro).
        /// </summary>
        internal static string InserirAbastecimento {
            get {
                return ResourceManager.GetString("InserirAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into distribuidora (nome)values(@nome).
        /// </summary>
        internal static string InserirDistribuidora {
            get {
                return ResourceManager.GetString("InserirDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into percurso (odometroinicial,odometrofinal,idveiculo,viagem,idabastecimentoinicial,idabastecimentofinal) values (@odometroinicial,@odometrofinal,@idveiculo,@viagem,@idabastecimentoinicial,@idabastecimentofinal).
        /// </summary>
        internal static string InserirPercurso {
            get {
                return ResourceManager.GetString("InserirPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into posto (idpessoajuridica,iddistribuidora, idendereco,observacoes) values (@idpessoajuridica, @iddistribuidora, @idendereco,@observacoes).
        /// </summary>
        internal static string InserirPosto {
            get {
                return ResourceManager.GetString("InserirPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into tipocombustivel (nome) values (@nome).
        /// </summary>
        internal static string InserirTipoCombustivel {
            get {
                return ResourceManager.GetString("InserirTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into veiculo(placa,renavam,cor,modelo,marca) values (@placa,@renavam,@cor,@modelo,@marca).
        /// </summary>
        internal static string InserirVeiculo {
            get {
                return ResourceManager.GetString("InserirVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from abastecimento where id = @id.
        /// </summary>
        internal static string SelecionarAbastecimento {
            get {
                return ResourceManager.GetString("SelecionarAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from distribuidora where id = @id.
        /// </summary>
        internal static string SelecionarDistribuidora {
            get {
                return ResourceManager.GetString("SelecionarDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select idabastecimentofinal from percurso where id = @id.
        /// </summary>
        internal static string SelecionarIdAbastecimentoFinalPercurso {
            get {
                return ResourceManager.GetString("SelecionarIdAbastecimentoFinalPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,odometroinicial,odometrofinal,idveiculo,viagem,idabastecimentoinicial,idabastecimentofinal from percurso where id = @id.
        /// </summary>
        internal static string SelecionarPercurso {
            get {
                return ResourceManager.GetString("SelecionarPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,iddistribuidora,idendereco,idpessoajuridica,observacoes from posto where id =@id.
        /// </summary>
        internal static string SelecionarPosto {
            get {
                return ResourceManager.GetString("SelecionarPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from tipocombustivel where id = @id.
        /// </summary>
        internal static string SelecionarTipoCombustivel {
            get {
                return ResourceManager.GetString("SelecionarTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from distribuidora order by nome.
        /// </summary>
        internal static string SelecionarTodasDistribuidoras {
            get {
                return ResourceManager.GetString("SelecionarTodasDistribuidoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from abastecimento order by data desc.
        /// </summary>
        internal static string SelecionarTodosAbastecimentos {
            get {
                return ResourceManager.GetString("SelecionarTodosAbastecimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,odometroinicial,odometrofinal,idveiculo,viagem,idabastecimentoinicial,idabastecimentofinal from percurso order by id.
        /// </summary>
        internal static string SelecionarTodosPercursos {
            get {
                return ResourceManager.GetString("SelecionarTodosPercursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,iddistribuidora,idendereco,idpessoajuridica,observacoes from posto order by id.
        /// </summary>
        internal static string SelecionarTodosPostos {
            get {
                return ResourceManager.GetString("SelecionarTodosPostos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from tipocombustivel order by nome.
        /// </summary>
        internal static string SelecionarTodosTiposCombustivel {
            get {
                return ResourceManager.GetString("SelecionarTodosTiposCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from veiculo order by modelo.
        /// </summary>
        internal static string SelecionarTodosVeiculos {
            get {
                return ResourceManager.GetString("SelecionarTodosVeiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from percurso where id IN (select max(id) from percurso).
        /// </summary>
        internal static string SelecionarUltimoPercurso {
            get {
                return ResourceManager.GetString("SelecionarUltimoPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from veiculo where id = @id.
        /// </summary>
        internal static string SelecionarVeiculo {
            get {
                return ResourceManager.GetString("SelecionarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table abastecimento (id int identity(1,1) not null primary key, idposto int, data datetime, observacoes ntext, tanquecheio bit, idtipoabastecimento int, valor decimal, valorlitro decimal).
        /// </summary>
        internal static string TabelaAbastecimento {
            get {
                return ResourceManager.GetString("TabelaAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table distribuidora (id int identity(1,1) primary key, nome nvarchar(80)).
        /// </summary>
        internal static string TabelaDistribuidora {
            get {
                return ResourceManager.GetString("TabelaDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table marca (id int identity(1,1) not null primary key, nome nvarchar(50), logotipo image).
        /// </summary>
        internal static string TabelaMarca {
            get {
                return ResourceManager.GetString("TabelaMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table percurso (id int identity(1,1) not null primary key, odometroinicial bigint, odometrofinal bigint, idveiculo int, viagem bit, idabastecimentoinicial int, idabastecimentofinal int).
        /// </summary>
        internal static string TabelaPercurso {
            get {
                return ResourceManager.GetString("TabelaPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table posto (id int identity(1,1) not null primary key, iddistribuidora int, idendereco int, idpessoajuridica int, observacoes nvarchar(255)).
        /// </summary>
        internal static string TabelaPosto {
            get {
                return ResourceManager.GetString("TabelaPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table tipocombustivel (id int identity(1,1) not null primary key, nome nvarchar(50)).
        /// </summary>
        internal static string TabelaTipoCombustivel {
            get {
                return ResourceManager.GetString("TabelaTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table veiculo(id int identity(1,1), placa nvarchar(10), renavam nvarchar(20), cor nvarchar(20), modelo nvarchar(100), marca nvarchar(100)).
        /// </summary>
        internal static string TabelaVeiculo {
            get {
                return ResourceManager.GetString("TabelaVeiculo", resourceCulture);
            }
        }
    }
}
